# borrowed from https://cloud.weave.works/k8s/scope.yaml?k8s-version=1.9.3
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weave-scope-app
  labels:
    name: weave-scope-app
    app: weave-scope
    weave-cloud-component: scope
    weave-scope-component: app
  namespace: weave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weave-scope
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: weave-scope-app
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: app
    spec:
      containers:
        - name: app
          args:
            - '--no-probe'
          env: []
          image: weaveworks/scope:1.11.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4040
              protocol: TCP
      tolerations:
      - key: monitoring
        operator: Equal
        value: prometheus
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - "monitoring"
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
